name: Build
on: [workflow_call, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1161
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node deps
        run: npm install
      - name: "Set env var"
        run: |
          echo "COMMIT_REF=$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build
        run: npx shadow-cljs release app worker
