name: Test, build and deploy
on: [workflow_dispatch]
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  lint-and-format-check:
    uses: ./.github/workflows/lint-and-format.yml
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [tests, lint-and-format-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1161
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install node deps
        run: npm install
      - name: "Set env var"
        run: |
          echo "COMMIT_REF=$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build
        run: npx shadow-cljs release app worker
      - name: Deploy on Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod --message "From GH at $COMMIT_REF"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
