name: Lint and format check
on: [workflow_call, workflow_dispatch]
jobs:
  lint-and-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.11.1.1161
          clj-kondo: 2022.05.31
      - name: clj-kondo lint
        run: clj-kondo --lint src test
      - name: Check format
        run: clojure -M:format/cljfmt-check
