name: Run tests, lint, format check and build
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'resources/**'
      - 'public/**'
      - 'deps.edn'
      - 'package.json'
      - 'shadow-cljs.edn'
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  lint-and-format-check:
    uses: ./.github/workflows/lint-and-format.yml
  build:
    uses: ./.github/workflows/build.yml
