name: Run tests and build
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'deps.edn'
      - 'shadow-cljs.edn'
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  lint-and-format-check:
    uses: ./.github/workflows/lint-and-format.yml
  build:
    uses: ./.github/workflows/build.yml
